config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get '/home/about' => "homes#about", as: 'about'
  resources :books
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

    has_one_attached :image
    belongs_to :user

    def get_image
        unless image.attached?
            file_path = Rails.root.join('app/assets/images-2/no_image.jpg')
            image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy

  validates :name, length: { minimum:2, maximum:20 }, uniqueness: true
  validates :introduction, length: { maximum:50 }

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images-2/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:about, :top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user_book, only: [:edit, :update]

  # 新規登録画面
  def new
  end
  # 新規登録=>DBへ内容保存
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to @book
    else
      @books = Book.all
      render :index
    end
  end

  # 一覧表示
  def index
    @books = Book.all
    @book = Book.new

  end

  # 詳細ページ
  def show
    @book = Book.find(params[:id])
  end

  # 詳細編集ページ
  def edit
    @book = Book.find(params[:id])
  end
  # 編集内容更新処理
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to @book
    else
      render :edit
    end
  end

  # 削除機能
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  # ストロングパラメーター設定
  private
  def book_params
    params.require(:book).permit(:image, :title, :body)
  end

 def is_matching_login_user_book
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to books_path
    end
 end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<!--登録-->
<%= form_with model: Book do |form| %>
  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div class="form-group">
    <%= form.label :opinion %><br>
    <%= form.text_area :body %>
  </div>

  <div class="form-group">
    <%= form.submit 'Create Book', class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5  mx-auto">
      <h1>Editing Book</h1>
      <!--varidation-->
      <% if @book.errors.any? %>
        <%= @book.errors.count %>errors prohibited this book from being saved:
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
          <br>
      <% end %>

      <!--更新-->
      <%= form_with model: @book do |form| %>
        <div class="form-group">
          <%= form.label :title %><br>
          <%= form.text_field :title %>
        </div>

        <div class="form-group">
          <%= form.label :opinion %><br>
          <%= form.text_area :body %>
        </div>

        <div class="form-group">
          <%= form.submit 'Update Book', class: "btn btn-success" %>
        </div>
      <% end %>

      <div>
        <%= link_to 'Show', book_path %>  |
        <%= link_to 'Back', books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <!--varidation-->
  <% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this book from being saved:
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      <br>
  <% end %>

  <div class="row">
    <div class="col-md-3">
      <!--ユーザーの詳細画面-->
      <%= render 'users/user_info', user: current_user %>

      <!--新規投稿画面-->
      <h2 class="mt-3">New book</h2>
      <%= render partial: 'form' %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

       <% @books.each do |book| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
              </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body%></td>
          </tr>
        </tbody>
       <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>新規投稿</h1>
<!--users/showへ表示させるため、コード移行-->

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <!--ユーザーの詳細画面-->
      <%= render 'users/user_info', user: @book.user %>

      <!--新規投稿画面-->
      <h2 class="mt-3">New book</h2>
      <%= render partial: 'form' %>
    </div>




    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
            <tbody>
              <tr>
                <td>
                  <%= image_tag @book.user.get_profile_image(100,100) %><br>
                  <%= link_to @book.user.name, user_path(@book.user.id) %>
                </td>
                <td><%= link_to @book.title %></td>
                <td><%= @book.body %></td>
                <% if @book.user == current_user %>
                  <td><%= link_to 'Edit', edit_book_path(@book), class:"btn btn-success" %></td>
                  <td><%= link_to 'Destroy', book_path(@book), method: :delete, class:"btn btn-danger", "data-confirm" => "Are you sure？" %></td>
                <% end %>
              </tr>
            </tbody>
        </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="mx-3 mx-auto">
      Welcome to
      <i class="fa-solid fa-book"></i>
    　<strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
    <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8  col-xl-6">
            <h1>
            welcome to <i class="fa-solid fa-book"></i>Bookers !!
            </h1>
            <p>In <i class="fa-solid fa-book"></i>Bookers,</p>

            <p>you can share and exchange your opinions , inpressions , and emotions</p>
            <p>about various books!</p>

            <div class="btn-wrapper col-10 mx-auto">
                <div class="row">
                    <%= link_to 'Log in', new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign-in" %>
                </div>
                <div class="row">
                    <%= link_to 'Sign up',new_user_registration_path, class:"btn btn-success btn-sm btn-block mb-3 sign-up" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/97b01a7c97.js" crossorigin="anonymous"></script>
    <!--実装変更-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <!--ログイン後のホーム画面-->
                <li class="nav-link text-light">
                  <%= link_to user_path(current_user.id) do %>
                    <i class="fa-solid fa-home" style="color: #51261f;"></i> Home
                  <% end %>
                </li>

                <!--ログイン後のユーザーの一覧-->
                <li class="nav-link text-light">
                  <%= link_to users_path do %>
                    <i class="fa-solid fa-users"></i> Users
                  <% end %>
                </li>

                <!--ログイン後のBooksの一覧-->
                <li class="nav-link text-light">
                  <%= link_to books_path do %>
                    <i class="fa-solid fa-book-open"></i> Books
                  <% end %>
                </li>

                <!--ログアウト-->
                <li class="nav-link text-light">
                  <%= link_to destroy_user_session_path, method: :delete  do %>
                    <i class="fa-solid fa-sign-out-alt"></i> Log out
                  <% end %>
                </li>
              <% else %>
                <!--Home画面の表示-->
                <li class="nav-link text-light">
                  <%= link_to  root_path  do %>
                    <i class="fa-solid fa-home" style="color: #fff;"></i> Home
                  <% end %>
                </li>

                <!--About画面の表示-->
                <li class="nav-link text-light">
                  <%= link_to about_path do %>
                    <i class="fa-solid fa-link" style="color: #fff"></i> About
                  <% end %>

                  <li class="nav-link text-light">
                  <%= link_to  new_user_registration_path do %>
                    <i class="fa-solid fa-user-plus" style="color: #fff"></i> Sign up
                  <% end %>
                </li>

                <li class="nav-link text-light">
                  <%= link_to new_user_session_path do%>
                    <i class="fa-solid fa-sign-in-alt" style="color: #fff"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <div>
        <%= flash[:notice] %>
        <%= yield %>
      </div>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/_user_info.html.erb
<!--ユーザーの詳細画面-->
<div>
  <h2>User Info</h2>
  <%= image_tag user.get_profile_image(100,100) %>

  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <td><%= user.name %></td>
      </tr>
      <tr>
        <th>introdaction</th>
        <td><%= user.introduction %></td>
      </tr>
    </tbody>
  </table>
</div>

<div class="row">
  <%= link_to  edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fa-solid fa-user-cog">プロフィール編集</i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 mx-auto">
      <h2>User Info</h2>
      <!--varidation-->
      <% if @user.errors.any? %>
        <%= @user.errors.count %>error prohibited this obj from being saved:
          <% @user.errors.full_messages.each do |message|%>
            <ul>
              <li><%= message %></li>
            </ul>
            <br>
          <% end %>
      <% end %>

      <%= form_with model:@user do |form| %>
          <div class="form-group">
            <label for="inputName">Name</label><br>
            <%= form.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
          </div>

          <div class="form-group">
            <label for="inputImage">ProfileImage</label><br>
            <%= form.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
          </div>
          <div class="form-group">
            <label for="introdaction">Introduction</label><br>
            <%= form.text_area :introduction %>
          </div>

          <div class="form-group">
            <%= form.submit 'Update User', class: 'btn btn-secondary' %>
          </div>
    　<% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <!--ユーザー詳細と新規投稿-->
    <div class="col-md-3">
      <!--ユーザーの詳細画面-->
      <%= render 'user_info', user: current_user %>


      <!--新規投稿画面-->
      <h2 class="mt-3">New book</h2>
      　<%= render 'books/form', book: @book %>
    </div>

    <!--Usersテーブル-->
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <% @users.each do |user|%>
        <tbody>
          <tr>
            <td><%= image_tag user.get_profile_image(100,100) %></td>
            <td><%= user.name %></td>
            <td><%= link_to 'Show', user_path(user.id) %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <!--ユーザーの詳細画面-->
      <%= render 'user_info', user: @user %>

      <!--新規投稿画面-->
      <h2 class="mt-3">New book</h2>
      　<%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <!--ユーザーが投稿した内容の一覧-->
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

        <% @user.books.each do |book|%>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= image_tag book.user.get_profile_image(150,150) %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body%></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>